name: Shorter workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test django app
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Control code style with Flake8
      run: flake8 .
    - name: Run tests
      run: coverage run --source='.' manage.py test
    - name: Collect coverage
      run: coverage report
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3